[workspace]
resolver = "3"
members = ["w3b2-common"]

[workspace.dependencies]
# internal
w3b2-common = { path = "w3b2-common" }

# external
anchor-lang = "0.31.1"
borsh = "0.10.3"
solana-pubkey = "3.0.0"
