[workspace]
resolver = "3"
members = ["w3b2-bridge-program", "w3b2-common"]

[workspace.dependencies]
# internal
w3b2-common = { path = "w3b2-common" }

# external
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }
borsh = "0.10.3"
solana-pubkey = "3.0.0"
