# Docker Compose для режима отладки
version: '3.8'

services:
  solana-validator:
    environment:
      - RUST_LOG=debug
    command: >
      solana-test-validator 
      --reset 
      --ledger test-ledger 
      --log test-ledger/validator.log 
      --bind-address 0.0.0.0 
      --rpc-port 8899 
      --dynamic-port-range 8000-8020
      --log-level debug

  connector:
    environment:
      - RUST_LOG=debug
    command: >
      cargo run --release --bin w3b2-connector
      -- --log-level debug

  backend:
    environment:
      - NODE_ENV=development
      - DEBUG=*
      - RUST_LOG=debug
    command: >
      npm run dev

  frontend:
    environment:
      - NODE_ENV=development
      - GENERATE_SOURCEMAP=true
    command: >
      npm start
