# Docker Compose для production режима
version: '3.8'

services:
  solana-validator:
    restart: unless-stopped
    environment:
      - RUST_LOG=warn
    command: >
      solana-test-validator 
      --reset 
      --ledger test-ledger 
      --log test-ledger/validator.log 
      --bind-address 0.0.0.0 
      --rpc-port 8899 
      --dynamic-port-range 8000-8020
      --log-level warn

  connector:
    restart: unless-stopped
    environment:
      - RUST_LOG=info
    command: >
      cargo run --release --bin w3b2-connector
      -- --log-level info

  backend:
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DEBUG=
    command: >
      npm start

  frontend:
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - GENERATE_SOURCEMAP=false
    command: >
      npm start
