services:
  # Rust builder (сборка и артефакты)
  builder:
    build:
      context: .
      dockerfile: Dockerfile.rust.builder
      target: builder
    volumes:
      - ./target:/project/target   # сохраняем артефакты наружу
    profiles: ["builder"]

  # Solana Test Validator
  solana-validator:
    build:
      context: .
      dockerfile: Dockerfile.validator
    ports:
      - "8899:8899"  # RPC
      - "8900:8900"  # WebSocket
      - "8901:8901"  # Gossip
    volumes:
      - solana-ledger:/ledger
    networks:
      - w3b2-network
    profiles: ["validator", "deploy", "full"]

  # Деплой программы
  bridge-program:
    build:
      context: .
      dockerfile: Dockerfile.rust.builder
      target: builder
    depends_on:
      - solana-validator
    volumes:
      - solana-ledger:/ledger
    environment:
      - SOLANA_RPC_URL=http://solana-validator:8899
      - BRIDGE_KEYPAIR_B64=${BRIDGE_KEYPAIR_B64}
    networks:
      - w3b2-network
    command: ["bash", "/project/deploy.sh"]
    profiles: ["deploy", "full"]

  # W3B2 Connector
  connector:
    build:
      context: .
      dockerfile: Dockerfile.rust.builder
      target: builder
    depends_on:
      - solana-validator
      - bridge-program
    ports:
      - "50051:50051"
    volumes:
      - connector-data:/project/w3b2_db
    environment:
      - RPC_URL=http://solana-validator:8899
      - WS_URL=ws://solana-validator:8900
      - HOST=0.0.0.0
      - PORT=50051
    networks:
      - w3b2-network
    command: >
      bash -c "./target/release/w3b2-connector --config /project/config.toml"
    profiles: ["deploy", "full"]

  # Backend
  backend:
    user: "0:0"
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - connector
    ports:
      - "3001:3001"
      - "50052:50052"
    volumes:
      - ./w3b2-connector/proto:/project/w3b2-bridge-backend/proto:ro   
      - backend-data:/project/w3b2-bridge-backend/data
    environment:
      - NODE_ENV=production
      - PORT=3001
      - GRPC_PORT=50052
      - SOLANA_RPC_URL=http://solana-validator:8899
      - CONNECTOR_GRPC_URL=connector:50051
      - PROGRAM_ID=3LhCu6pXXdiwpvBUrFKLxCy1XQ5qyE7v6WSCLbkbS8Dr
      - DATABASE_URL=sqlite:./data/database.sqlite
      - ENCRYPTION_KEY=your-32-character-secret-key-here
    networks:
      - w3b2-network
    profiles: ["backend", "full"]

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
      - REACT_APP_WS_URL=ws://localhost:3001
      - GENERATE_SOURCEMAP=false
    networks:
      - w3b2-network
    profiles: ["frontend", "full"]

volumes:
  solana-ledger:
  connector-data:
  backend-data:

networks:
  w3b2-network:
    driver: bridge
