# RPC endpoints
rpc_url = "http://127.0.0.1:8899"
ws_url = "ws://127.0.0.1:8900"

host = "127.0.0.1"
port = 50051
# Max slots to go back during catch-up (None = unlimited)
max_catchup_depth = 1000 # или оставь пустым для None

# Max age of a funding request in minutes
max_request_age_minutes = 60

# Poll interval in seconds for catch-up worker
poll_interval_secs = 3

# Commitment level: "Processed", "Confirmed", "Finalized"
commitment = "Confirmed"

# Max number of signatures to fetch per RPC call
max_signature_fetch = 500

# Data and log directories
data_dir = "./w3b2_db"
log_dir = "Logs"
