# Configuration for the w3b2-connector library core.

# This section contains all settings related to the Solana network connection.
[solana]

# The HTTP RPC endpoint of the Solana cluster.
# Example for local validator: "http://127.0.0.1:8899"
# Example for Solana Devnet: "https://api.devnet.solana.com"
rpc-url = "http://127.0.0.1:8899"

# The WebSocket endpoint for real-time event subscriptions.
# Example for local validator: "ws://127.0.0.1:8900"
# Example for Solana Devnet: "wss://api.devnet.solana.com"
ws-url = "ws://127.0.0.1:8900"

# The commitment level to use for fetching transactions.
# Determines how finalized a block must be before it's considered confirmed.
# Possible values: "Processed", "Confirmed", "Finalized"
commitment = "Confirmed"


# This section contains settings for the event synchronizer, which fetches
# both historical (catch-up) and live events.
[synchronizer]


#| Time Interval | Theoretical Maximum Blocks (at 400 ms/block, 100% success) | Realistic Block Estimate (at ~2.45 BPS, observed average) | Implied Slot Success Rate |
#|----------|---------|----------|--------|
#| 8 hours  | 72,000  | ~70,560  | ~98.0% |
#| 12 hours | 108,000 | ~105,840 | ~98.0% |
#| 24 hours | 216,000 | ~211,680 | ~98.0% |

# (Optional) The maximum number of historical slots to scan backwards.
# If this is set, the catch-up worker will not process transactions older than
# (current_slot - max_catchup_depth).
# Comment out or remove this line to scan the entire history.
max-catchup_depth = 72000

# The interval in seconds at which the catch-up worker polls for new transaction signatures.
poll-interval_secs = 3

# The maximum number of transaction signatures to fetch in a single RPC call.
# The maximum allowed by public RPC nodes is typically 1000.
max-signature_fetch = 1000
